/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Hero`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(client)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(client)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(promoter)'}/Explore` | `/Explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(promoter)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(promoter)'}/profile` | `/profile`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/Hero`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(client)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(client)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(promoter)'}/Explore` | `/Explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(promoter)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(promoter)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/Hero${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signup${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `${'/(client)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(client)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(promoter)'}/Explore${`?${string}` | `#${string}` | ''}` | `/Explore${`?${string}` | `#${string}` | ''}` | `${'/(promoter)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(promoter)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Hero`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(client)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(client)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(promoter)'}/Explore` | `/Explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(promoter)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(promoter)'}/profile` | `/profile`; params?: Router.UnknownInputParams; };
    }
  }
}
